name: Pre-Release Binaries

on:
  push:
    tags:
      - 'v*.*.*-*'

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Build Tools
        if: runner.os == 'macOS'
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel
          npm install -g node-gyp@latest

      - name: Install system dependencies for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 make g++ build-essential libsqlite3-dev

      - name: Install system dependencies for Windows
        if: runner.os == 'Windows'
        run: |
          # Print system information for debugging
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version" /C:"System Type"
          # GitHub Actions Windows runners already have Visual Studio Build Tools installed
          echo "Using pre-installed Visual Studio Build Tools"
          # Install node-gyp globally
          npm install -g node-gyp
          # Configure node-gyp to use the Python we just set up
          $pythonPath = (Get-Command python).Path
          echo "Python path: $pythonPath"

          # Create or update .npmrc file with Python path and MSVS version
          echo "python=$pythonPath" | Out-File -Append -Encoding utf8 $env:USERPROFILE\.npmrc
          echo "msvs_version=2019" | Out-File -Append -Encoding utf8 $env:USERPROFILE\.npmrc

          # Show the .npmrc file
          echo "Contents of .npmrc:"
          Get-Content $env:USERPROFILE\.npmrc

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          cd release/app
          npm install --ignore-scripts
          cd ../..

      - name: Rebuild native modules for macOS
        if: matrix.os == 'macos-latest'
        run: |
          cd release/app
          npx electron-rebuild -f -w better-sqlite3 -v 26.6.10
          cd ../..

      - name: Rebuild native modules for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd release/app
          npx electron-rebuild -f -w better-sqlite3 -v 26.6.10
          cd ../..

      - name: Rebuild native modules for Windows
        if: matrix.os == 'windows-latest'
        run: |
          cd release/app
          # Rebuild better-sqlite3 for Electron
          npx electron-rebuild -f -w better-sqlite3 -v 26.6.10

          # Check the installed packages
          npm list better-sqlite3

          # Check the binary module
          if (Test-Path -Path "node_modules\better-sqlite3\build\Release") {
            dir node_modules\better-sqlite3\build\Release
          } else {
            echo "No .node files found in build\Release"
            # Check other possible locations
            dir node_modules\better-sqlite3 -Recurse -Filter "*.node" | Select-Object FullName
          }

          cd ..\..

      - name: Build Electron app for macOS
        if: matrix.os == 'macos-latest'
        run: npm run package:mac

      - name: Build Electron app for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: npm run package:linux

      - name: Build Electron app for Windows
        if: matrix.os == 'windows-latest'
        run: npm run package:win

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            ./release/build/*.AppImage
            ./release/build/*.exe
            ./release/build/*.dmg
            ./release/build/*.zip

  pre-release:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate changelog
        run: npx auto-changelog -p

      - name: Download macOS Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-macos-latest
          path: ./release/build/macos

      - name: Download Windows Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-windows-latest
          path: ./release/build/windows

      - name: Download Ubuntu Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-ubuntu-latest
          path: ./release/build/ubuntu

      - name: List downloaded files
        run: ls -R ./release/build

      - name: Create GitHub Pre-Release
        id: create_pre_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./release/build/macos/*.dmg
            ./release/build/ubuntu/*.AppImage
            ./release/build/ubuntu/*.zip
            ./release/build/windows/*.exe
            ./release/build/windows/*.msi
          tag_name: ${{ github.ref }}
          name: Pre-Release ${{ github.ref }}
          body_path: ./CHANGELOG.md
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
