name: Pre-Release Binaries

on:
  push:
    tags:
      - 'v*.*.*-pre'

jobs:
  pre-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Python dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils build-essential

      - name: Install Python dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install python@3.9
          python3 -m pip install --upgrade pip
          python3 -m pip install distutils


      - name: Build/release Electron app
        uses: DarkGuy10/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a pre-release version (e.g. "v1.0.0-pre"),
          # release the app after building
          release: ${{ contains(github.ref, '-pre') }}
