name: Run Tests

on:
  push:
    branches: ['*']

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [20]
    uses: ./.github/workflows/setup-environment.yml
    with:
      os: ${{ matrix.os }}
      node-version: ${{ matrix.node-version }}

  run-tests-macos:
    needs: test
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests
        run: npm test

  run-tests-linux:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests
        run: npm test

  run-tests-windows:
    needs: test
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests
        run: npm test
